#!/usr/bin/env python
# sys - System-specific parameters and functions
# Provides access to some variables used or maintained by the interpreter and 
# to functions that interact strongly with the interpreter. 
# It is always available 
import sys

# os - Miscellaneous operating system interafces
# Provides a portable way of using operating system dependent functinoality.
import os

# os.environ
# A mapping object representing the string environment. This mapping is captured 
# the first time the os module is imported, typically during Python startup as part 
# of changes made by modifying os.environ directly.
os.environ['CERBERO_UNINSTALLED']='1'

# sys.path
# A list of strings that specified the search path for modules. Initialized from the # environment variable PYTHONPATH, plus an installation-dependent default.

# __file__
# The pathname of the file from which the module was loaded. Another method is 
# sys.argv[0], All maybe relative
sys.path.insert(0, os.path.dirname(__file__))


from cerbero.main import main
main()
